findit/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from findit.models import User


class RegistrationForm(FlaskForm):
    name = StringField('First Name',
                           validators=[DataRequired(), Length(min=2, max=20)])
    surname = StringField('Second Name',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')


class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')


class UpdateContactInfoForm(FlaskForm):
    email = StringField('Email', [Email()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    phone = StringField('Phone')
    skype = StringField('Skype')
    github = StringField('Github')
    submit = SubmitField('Update')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')


class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('There is no account with that email. You must register first.')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')

findit/vacancies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, RadioField
from wtforms.validators import DataRequired
from findit.models import english_levels


class VacancyForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    city = StringField('City', validators=[DataRequired()])
    experience = StringField('Required experience', validators=[DataRequired()])
    skills = StringField('Required skills', validators=[DataRequired()])
    english_level = RadioField('Label', choices=english_levels)
    description = TextAreaField('Description', validators=[DataRequired()])
    position = StringField('Position', validators=[DataRequired()])
    salary = StringField('Salary', validators=[DataRequired()])
    submit = SubmitField('Submit')

findit/main/routes.py
from flask import render_template, Blueprint, request, url_for, redirect, jsonify, flash
from flask_login import login_required, current_user
from findit.models import Vacancy, User, city_names, employment_types, english_levels, technology_titles
from findit import db

main = Blueprint('main', __name__)


@main.route("/admin/create_tables")
def create_tables():
    try:
        db.create_all()
        flash('Database fields were created!', 'success')
    except:
        flash('An error occurred during creation!', 'failure')
    return render_template('home.html', title='Home')


@main.route("/tutorial")
def tutorial():
    return render_template('tutorial_layout.html', title='Tutorial')


@main.route("/admin/drop_tables")
def drop_tables():
    try:
        db.drop_all()
        flash('Database fields were dropped!', 'success')
    except:
        flash('An error occurred during dropping!', 'failure')
    return render_template('home.html', title='Home')


@main.route("/about")
def about():
    return render_template('about.html', title='About')


@main.route("/")
@main.route("/home")
def home():
    if current_user.is_authenticated:
        return redirect(url_for('main.vacancies'))
    return render_template('home.html', title='Home')


@main.route("/cities")
def cities():
    response = jsonify(city_names)
    response.headers.add('Access-Control-Allow-Origin', '*')
    return response


@main.route("/employment_types")
def employment_types():
    response = jsonify(employment_types)
    response.headers.add('Access-Control-Allow-Origin', '*')
    return response


@main.route("/english_levels")
def english_levels():
    response = jsonify(english_levels)
    response.headers.add('Access-Control-Allow-Origin', '*')
    return response


@main.route("/technologies")
def technologies():
    response = jsonify(technology_titles)
    response.headers.add('Access-Control-Allow-Origin', '*')
    return response


@main.route("/vacancies")
@login_required
def vacancies():
    page = request.args.get('page', 1, type=int)
    vacancies = Vacancy.query.paginate(page=page, per_page=5)
    return render_template('vacancies.html', title='Vacancies', vacancies=vacancies)


@main.route("/candidates")
def candidates():
    page = request.args.get('page', 1, type=int)
    candidates = User.query.paginate(page=page, per_page=5)
    return render_template('candidates.html', title='Vacancies', candidates=candidates)

findit/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from findit import db, bcrypt
from findit.models import User, Vacancy
from findit.users.forms import (RegistrationForm, LoginForm, UpdateContactInfoForm,
                                RequestResetForm, ResetPasswordForm)
from findit.users.utils import save_picture, send_reset_email
from findit.search import find_suitable_vacancies
from findit.config import Config

users = Blueprint('users', __name__)


@users.route("/suggested_vacancies")
@login_required
def suggest_vacancies():
    vacancies = find_suitable_vacancies(current_user)
    return render_template('suggested_vacancies.html', title='Find your vacancy', vacancies=vacancies)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(name=form.name.data, surname=form.surname.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Ваш аккаунт було створено! Ви маєте можливість увійти в систему', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Вхід в систему був не успішний. Будь ласка, перевірте правильність вводу електронної пошти та паролю', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/profile", methods=['GET', 'POST'])
@login_required
def profile():
    if request.method == 'POST':
        updated_entities = {}

        for key, value in request.form.items():
            if not value == '':
                updated_entities[key] = value

        User.query.filter_by(id=current_user.id).update(updated_entities)
        db.session.flush()
        db.session.commit()
        flash('Інформація по вашому профілю було оновлено!', 'success')
        return redirect(url_for('users.profile'))
    return render_template('profile.html', title='Profile', backend_url=Config.WEBPAGE_URL)


@users.route("/contact_info", methods=['GET', 'POST'])
@login_required
def contact_info():
    form = UpdateContactInfoForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.email = form.email.data
        current_user.telephone = form.phone.data
        current_user.skype = form.skype.data
        current_user.github = form.github.data
        db.session.commit()
        flash('Вашу контактну інформацію було оновлено!', 'success')
        return redirect(url_for('users.contact_info'))
    elif request.method == 'GET':
        form.email.data = current_user.email
        form.phone.data = current_user.telephone
        form.skype.data = current_user.skype
        form.github.data = current_user.github
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('contact_info.html', title='Update contact info',
                           image_file=image_file, form=form)


@users.route("/user/<string:id>")
def user(id):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(id=id).first_or_404()
    vacancies = Vacancy.query.filter_by(author=user) \
        .order_by(Vacancy.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' + user.image_file)
    return render_template('user.html', vacancies=vacancies, user=user, image_file=image_file)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

findit/vacancies/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from findit import db
from findit.models import Vacancy
from findit.vacancies.forms import VacancyForm
from findit.search import find_suitable_users
from findit.config import Config

vacancies = Blueprint('vacancies', __name__)


@vacancies.route("/vacancy/new", methods=['GET', 'POST'])
@login_required
def new_vacancy():
    if request.method == 'POST':
        entries = {}

        for key, value in request.form.items():
            if not value == '':
                entries[key] = value

        vacancy = Vacancy(**entries)
        vacancy.author = current_user
        db.session.add(vacancy)
        db.session.commit()
        flash('Вашу вакансію було додано!', 'success')
        return redirect(url_for('main.vacancies'))
    return render_template('create_vacancy.html', title='New vacancy', legend='Submit vacancy', backend_url=Config.WEBPAGE_URL)


@vacancies.route("/vacancy/<int:vacancy_id>")
def preview_vacancy(vacancy_id):
    vacancy = Vacancy.query.get_or_404(vacancy_id)
    users = find_suitable_users(vacancy)
    return render_template('vacancy.html', title=vacancy.title, vacancy=vacancy, users=users)


@vacancies.route("/vacancy/<int:vacancy_id>/update", methods=['GET', 'POST'])
@login_required
def update_vacancy(vacancy_id):
    vacancy = Vacancy.query.get_or_404(vacancy_id)
    if vacancy.author != current_user:
        abort(403)
    form = VacancyForm()
    if form.validate_on_submit():
        vacancy.title = form.title.data,
        vacancy.city = form.city.data,
        vacancy.experience = form.experience.data,
        vacancy.skills = form.skills.data,
        vacancy.english_level = form.english_level.data,
        vacancy.description = form.description.data
        db.session.commit()
        flash('Your vacancy has been updated!', 'success')
        return redirect(url_for('vacancies.preview_vacancy', vacancy_id=vacancy.id))
    elif request.method == 'GET':
        vacancy.title = form.title.data,
        vacancy.city = form.city.data,
        vacancy.experience = form.experience.data,
        vacancy.skills = form.skills.data,
        vacancy.english_level = form.english_level.data,
        vacancy.description = form.description.data
    return render_template('create_vacancy.html', title='Update Vacancy', form=form, legend='Update Vacancy')


@vacancies.route("/vacancy/<int:vacancy_id>/delete", methods=['POST'])
@login_required
def delete_vacancy(vacancy_id):
    vacancy = Vacancy.query.get_or_404(vacancy_id)
    if vacancy.publisher != current_user:
        abort(403)
    db.session.delete(vacancy)
    db.session.commit()
    flash('Вашу вакансію було видалено!', 'success')
    return redirect(url_for('main.home'))

findit/templates/candidates.html
{% extends "layout.html" %}
{% block content %}
<div class="col-md-3 col-sm-0">&#8203;</div>
<div class="col-md-6 col-sm-12" style="margin-top: 3%">
    <h1>Кандидати на FintIT</h1>

    <h1>TODO: update this shit with backend-provided fields!</h1>
    <hr>

    <div class="col-md-12 col-sm-12" style="margin-top: 5%; font-size: 14pt;">
        <div class="inbox-date pull-right">20.09.2019</div>
        <div class="list-jobs__title"><a class="profile"> Разработчик С++ </a></div>
        <div class="list-jobs__details tiny-profile-details" style="font-size: 10pt">
            <span v-for="city in user.cities_arr"> Lviv, Kyiv , </span>
            <span class="profile-details-salary"> 700$</span>,
            <span> 2 роки досвіду</span>,
            <span> Intermediate  </span>
        </div>
        <div style="word-break: break-word;"> user.experience_description </div>
        <div><span v-for="skill in user.key_skills_arr">  skill , </span> </div>
        <div style="font-style: italic"> user.desires_description </div>
    </div>


    <div class="col-md-12 col-sm-12" style="margin-top: 5%; font-size: 14pt;">
        <div class="inbox-date pull-right">DATE</div>
        <div class="list-jobs__title"><a class="profile"> user.position </a></div>
        <div class="list-jobs__details tiny-profile-details" style="font-size: 10pt">
            <span v-for="city in user.cities_arr"> city , </span>
            <span class="profile-details-salary"> user.salary $</span>,
            <span> user.years_of_experience  роки досвіду</span>,
            <span> user.english_level  </span>
        </div>
        <div style="word-break: break-word;"> user.experience_description </div>
        <div><span v-for="skill in user.key_skills_arr">  skill , </span> </div>
        <div style="font-style: italic"> user.desires_description </div>
    </div>


</div>


{% endblock %}

findit/templates/home.html
{% extends "layout.html" %}
{% block content %}

<div class="container">
    <center>
        <h1 class="jobs-push-hero__headline" style="margin-top: 5%">
            FindIT - пошук роботи для студентів кафедри ІСМ
        </h1>
    </center>
    <hr>

    <div class="jobs-push-form-wrapper" style="margin-top: 5%">
        <div class="container" align="center">

            <a class="btn btn-primary btn-lg v4__submit" href="{{ url_for('users.register') }}">Розпочати
                <span class="glyphicon glyphicon-globe"></span>
            </a>

        </div>
    </div>

</div>
</div>
{% endblock %}

findit/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">

  {% if title %}
  <title>FindIT - {{ title }}</title>
  {% else %}
  <title>FindIT</title>
  {% endif %}

  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='Vue/DonwloadedVue.js') }}"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>


  <script type="text/javascript" src="{{ url_for('static', filename='Bootstrap/JS/Bootstrap-min-js.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='Ajax.js') }}"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='CSS/BasicStyle.css') }}">


</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-default bg-steel fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">FindIT</a>
        </div>
        <ul class="nav navbar-nav">
          {% if current_user.is_authenticated %}
          {% else %}
          <li id="main.home"><a href="{{ url_for('main.home') }}">Домашня Сторінка</a></li>
          {% endif %}
          {% if current_user.is_authenticated %}
          <li id="users.profile"><a href="{{ url_for('users.profile') }}">Профіль користувача</a></li>
          <li id="vacancies.new_vacancy"><a href="{{ url_for('vacancies.new_vacancy') }}">Розмістити вакансію</a></li>
          <li id="main.vacancies"><a href="{{ url_for('main.vacancies') }}">Список вакансій</a></li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{{ url_for('main.tutorial') }}"> <span class="glyphicon glyphicon-question-sign"></span></a></li>
          {% if current_user.is_authenticated %}
          <li id="users.logout"><a href="{{ url_for('users.logout') }}">Вийти</a></li>
          {% else %}
          <li id="users.login"><a href="{{ url_for('users.login') }}">Увійти</a></li>
          <li id="users.register"><a href="{{ url_for('users.register') }}">Зареєструватися</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>


  <div class="col-sm-12">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</body>
<script>
  $(document).ready(function () {
    document.getElementById("{{request.endpoint}}").classList.add("active");
  })
</script>

</html>

findit/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="col-md-4 col-sm-4">&#8203;</div>
    <div class="col-md-4 col-sm-4" style="margin-top: 3%">
        <legend>Увійти</legend>
        <div class="content-section">

            <form class="tab-pane fade in active" method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="form-group">
                        <label for="SignIn_Email">Електронна пошта:</label>
                        {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.email(class="form-control form-control-lg", id="SignIn_Email", placeholder="Введіть емейл") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="SignIn_Pwd">Пароль:</label>
                        {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.password(class="form-control form-control-lg", id="SignIn_Pwd", placeholder="Введіть пароль") }}
                        {% endif %}
                    </div>
                    <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label", value="запам'ятати мене") }}
                    </div>
                </fieldset>

                <div class="form-group">
                    {{ form.submit(class="btn btn-success", value="Увійти") }}
                </div>
            </form>
        </div>
    </div>
<div class="border-top pt-3">
    <small class="text-muted">
        Не маєте аккаунту? <a class="ml-2" href="{{ url_for('users.register') }}">Зареєструватися</a>
    </small>
</div>
{% endblock content %}

findit/templates/suggested_vacancies.html
{% extends "layout.html" %}
{% block content %}

<div class="col-md-3 col-sm-0">&#8203;</div>
<div class="col-md-6 col-sm-12" style="margin-top: 3%">

  <h2>Вакансії за Вашим профілем</h2>
  <ul class="nav nav-pills" style="margin: 1.5em 0 1em;">
    <li>
      <a href="{{ url_for('main.vacancies') }}">Всі вакансії</a></li>
    <li class="active">
      <a href="{{ url_for('users.suggest_vacancies') }}">Вакансії за моїм профілем</a></li>
  </ul>
  <legend></legend>

  {% for vacancy in vacancies %}
  <div class="col-md-12 col-sm-12" style="margin-top: 5%; font-size: 12pt;">
    <div class="inbox-date pull-right">{{ vacancy.date_posted.strftime('%Y-%m-%d') }}</div>

    <div class="list-jobs__title">
      <a class="profile"
        href="{{ url_for('vacancies.preview_vacancy', vacancy_id=vacancy.id) }}">{{ vacancy.title }}</a>
    </div>

    <div class="list-jobs__details tiny-profile-details" style="font-size: 9pt">
      <img class="circle_img article-img" style="width: 32px; height:32px;"
        src="{{ url_for('static', filename='profile_pics/' + vacancy.author.image_file) }}" />
      <a href="{{ url_for('users.user', id=vacancy.author.id) }}">{{ vacancy.author.name}}
        {{ vacancy.author.surname}}</a>, {{ vacancy.author.desired_position }} at {{ vacancy.company_name }}
           
        <span class="glyphicon glyphicon-map-marker"></span>
        <span>{{ vacancy.city }}</span>,
      <span>роки досвіду: {{ vacancy.experience }}, </span>
      <span>рівень англійської: {{ vacancy.english_level }}</span>
    </div>
  </div>
  {% endfor %}


</div>


{% endblock %}

findit/templates/vacancies.html
{% extends "layout.html" %}
{% block content %}

<div class="col-md-3 col-sm-0">&#8203;</div>
<div class="col-md-6 col-sm-12" style="margin-top: 3%">
  <h2>Вакансії на FindIT</h2>


  <ul class="nav nav-pills" style="margin: 1.5em 0 1em;">
    <li class="active">
      <a href="{{ url_for('main.vacancies') }}">Всі вакансії</a></li>
    <li>
      <a href="{{ url_for('users.suggest_vacancies') }}">Вакансії за моїм профілем</a></li>
  </ul>


  <legend></legend>

  {% for vacancy in vacancies.items %}
  <div class="col-md-12 col-sm-12" style="margin-top: 5%; font-size: 12pt;">
    <div class="inbox-date pull-right">{{ vacancy.date_posted.strftime('%Y-%m-%d') }}</div>

    <div class="list-jobs__title">
      <a class="profile"
        href="{{ url_for('vacancies.preview_vacancy', vacancy_id=vacancy.id) }}">{{ vacancy.title }}</a>
    </div>

    <div class="list-jobs__details tiny-profile-details" style="font-size: 9pt">
      <img class="circle_img article-img" style="width: 32px; height:32px;"
        src="{{ url_for('static', filename='profile_pics/' + vacancy.author.image_file) }}" />
      <a href="{{ url_for('users.user', id=vacancy.author.id) }}">{{ vacancy.author.name}}
          {{ vacancy.author.surname}}</a>, {{ vacancy.author.desired_position }} at {{ vacancy.company_name }}
             
      <span class="glyphicon glyphicon-map-marker"></span>
      <span>{{ vacancy.city }}</span>,
      <span>роки досвіду: {{ vacancy.experience }}, </span>
      <span>рівень англійської: {{ vacancy.english_level }}</span>
    </div>
  </div>


  {% endfor %}


  {% for page_num in vacancies.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
  {% if vacancies.page == page_num %}
  <a class="btn btn-info mb-4" href="{{ url_for('main.vacancies', page=page_num) }}">{{ page_num }}</a>
  {% else %}
  <a class="btn btn-outline-info mb-4" href="{{ url_for('main.vacancies', page=page_num) }}">{{ page_num }}</a>
  {% endif %}
  {% else %}
  ...
  {% endif %}

  {% endfor %}

</div>


{% endblock %}

findit/templates/vacancy.html
{% extends "layout.html" %}
{% block content %}


<div class="col-sm-2 col-sm-2">&#8203;</div>
<div class="col-sm-6 col-sm-6" style="margin-top: 3%">


  <a href="{{ url_for('main.vacancies') }}"> Всі вакансії</a>


  <hr>
  <h2>{{ vacancy.title }}</h2>


  <div class="list-jobs__details tiny-profile-details" style="font-size: 9pt">
    <img class="circle_img article-img" style="width: 32px; height:32px;"
      src="{{ url_for('static', filename='profile_pics/' + vacancy.author.image_file) }}" />
    <a href="{{ url_for('users.user', id=vacancy.author.id) }}">{{ vacancy.author.name}}
      {{ vacancy.author.surname}}</a>, {{ vacancy.author.desired_position }} at {{ vacancy.company_name }},
      
    <span class="glyphicon glyphicon-map-marker"></span>
    <span>{{ vacancy.city }}</span>,
    <span>роки досвіду: {{ vacancy.experience }}</span>,
    <span>{{ vacancy.english_level }}</span>
  </div>

  <hr>

  <div class="profile-page-section" style="font-size: 14pt">
    {{vacancy.short_description}}
    <br>
    <br>
    <br>
  </div>
  <div class="profile-page-section" style="font-size: 12pt">
    {{vacancy.description}}
    <br>
    <br>
    <br>
  </div>
  <div class="profile-page-section" style="font-size: 12pt">
    <p><b>Про компанію {{ vacancy.company_name }}</b></p>
    {{vacancy.about_company}}
    <br>
    <br>
    <br>
  </div>
  <div class="profile-page-section" style="font-size: 12pt">
    <p><b>Сайт компанії</b></p>
    <a href="{{ vacancy.company_page }}">{{ vacancy.company_page }}</a>
    <br>
    <br>
    <br>
  </div>
  <div>
    <p class="text-muted">
      <span class="glyphicon glyphicon-edit"></span>
      {{ vacancy.date_posted.strftime('%Y-%m-%d') }}
      <br>
    </p>
  </div>


</div>
<br>
<div class="container col-md-3 col-sm-4" style="margin-top: 3%">
  <h2>Найкращі кандидати</h2>

  {% for user in users %}


  <div class="list-jobs__details tiny-profile-details" style="font-size: 9pt;">
        <div class="col-sm-12" style="padding-left: 12px">
            <p>
                <img class="circle_img article-img" style="width: 32px; height:32px;"
                src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}" />
                <a href="{{ url_for('users.user', id=user.id) }}">{{ user.name }} {{ user.surname }}</a>
            </p>
        </div>

        <div class="list-jobs__details tiny-profile-details col-sm-12" style="font-size: 9pt;">
          <p>Навички: {{ user.skills }}</p>
          <p>Роки досвіду: {{ user.experience }}</p>
          <p>Рівень англійської: {{ user.english_level }}</p>
          <span class="profile-details-salary">{{ user.expected_salary }}$</span>
        </div>
  </div>
  {% endfor %}

</div>


  {% endblock %}